import type {
  Agent,
  AgentActivity,
  AIInstruction,
  AIStatus,
  Approval,
  BusinessGoal,
  BusinessRule,
  DashboardPreferences,
} from "@/types/intelligence";
export const demoAgents: Agent[] = [
  {
    id: "store",
    name: "Store Agent",
    purpose: "Make shopping feel effortless.",
    task: "Checking your mobile product pages",
    actions: 9,
    status: "Working",
    autonomy: "Ask before changes",
    lastActivity: "Found a possible conversion improvement",
  },
  {
    id: "research",
    name: "Research Agent",
    purpose: "Find your next good idea.",
    task: "Looking for products gaining momentum",
    actions: 12,
    status: "Working",
    autonomy: "Everyday tasks only",
    lastActivity: "Found 3 products worth researching",
  },
  {
    id: "ads",
    name: "Ads Agent",
    purpose: "Help every advertising euro go further.",
    task: "Analyzing Meta campaigns",
    actions: 24,
    status: "Working",
    autonomy: "Automatic within limits",
    lastActivity: "Flagged one ad with no purchases",
  },
  {
    id: "creative",
    name: "Creative Agent",
    purpose: "Turn good ideas into things people notice.",
    task: "Ready for your next creative brief",
    actions: 12,
    status: "Idle",
    autonomy: "Everyday tasks only",
    lastActivity: "Prepared 4 new concepts",
  },
  {
    id: "support",
    name: "Support Agent",
    purpose: "Give customers a helpful, human reply.",
    task: "Reviewing 24 customer conversations",
    actions: 42,
    status: "Working",
    autonomy: "Everyday tasks only",
    lastActivity: "Answered Sarah’s delivery question",
  },
  {
    id: "finance",
    name: "Finance Agent",
    purpose: "Keep an eye on what you actually earn.",
    task: "Calculating today’s profit",
    actions: 6,
    status: "Working",
    autonomy: "Ask before changes",
    lastActivity: "Updated today’s profit estimate",
  },
  {
    id: "operations",
    name: "Operations Agent",
    purpose: "Keep orders and stock moving.",
    task: "Checking inventory and delivery updates",
    actions: 24,
    status: "Working",
    autonomy: "Everyday tasks only",
    lastActivity: "Flagged 3 delayed orders",
  },
  {
    id: "competitor",
    name: "Competitor Agent",
    purpose: "Keep a little perspective on your market.",
    task: "Waiting for the next market review",
    actions: 8,
    status: "Idle",
    autonomy: "Ask before changes",
    lastActivity: "Reviewed 8 sample storefronts",
  },
];
export const aiStatus: AIStatus = {
  source: "demo",
  summary: "Everything is under control. You make the big calls.",
  tasks: [
    "Analyzing today’s ad performance…",
    "Checking 18 ad campaigns",
    "Reviewing 24 customer conversations",
    "Calculating today’s profit",
    "Looking for products gaining momentum",
    "Checking inventory",
    "Analyzing your store conversion",
  ],
};
export const demoActivities: AgentActivity[] = [
  {
    id: "live-1",
    agentId: "ads",
    action: "Found an ad losing money",
    detail: "€47 spent · 0 purchases",
    timeLabel: "Just now",
    kind: "insight",
    source: "demo",
  },
  {
    id: "live-2",
    agentId: "support",
    action: "Answered Sarah’s delivery question",
    detail: "12 sec response time",
    timeLabel: "2 min ago",
    kind: "completed",
    source: "demo",
  },
  {
    id: "live-3",
    agentId: "research",
    action: "Found 3 products worth researching",
    detail: "Travel accessories · Sample opportunities",
    timeLabel: "4 min ago",
    kind: "insight",
    source: "demo",
  },
  {
    id: "live-4",
    agentId: "store",
    action: "Found a possible conversion improvement",
    detail: "Make delivery details easier to find",
    timeLabel: "7 min ago",
    kind: "insight",
    source: "demo",
  },
  {
    id: "live-5",
    agentId: "finance",
    action: "Updated today’s profit",
    detail: "€1,284 estimated profit · Example event",
    timeLabel: "10 min ago",
    kind: "completed",
    source: "demo",
  },
];
export const nextDemoActivities: AgentActivity[] = [
  {
    id: "next-1",
    agentId: "operations",
    action: "Spotted two products running low",
    detail: "A stock reminder is ready to review",
    timeLabel: "Just now",
    kind: "insight",
    source: "demo",
  },
  {
    id: "next-2",
    agentId: "creative",
    action: "Prepared three new ad concepts",
    detail: "Ready for your feedback",
    timeLabel: "Just now",
    kind: "completed",
    source: "demo",
  },
  {
    id: "next-3",
    agentId: "ads",
    action: "Prepared a budget recommendation",
    detail: "Waiting for you · No budget changed",
    timeLabel: "Just now",
    kind: "approval",
    source: "demo",
  },
];
export const demoApprovals: Approval[] = [
  {
    id: "budget",
    agentId: "ads",
    title: "Increase “Summer Campaign” budget",
    change: "€200/day → €240/day",
    reason: "Strong profitability for 3 consecutive days.",
    effect: "More sales while staying within your target.",
    declineLabel: "Not now",
    status: "Pending",
  },
  {
    id: "refund",
    agentId: "support",
    title: "Refund customer",
    change: "€79.95",
    reason: "Package appears lost.",
    effect:
      "Help resolve the customer’s complaint. This amount is above the sample €50 approval limit.",
    declineLabel: "Reject",
    status: "Pending",
  },
];
export const businessGoals: BusinessGoal[] = [
  {
    id: "profit",
    label: "Maximize profit",
    description: "Keep more of what you earn.",
  },
  { id: "revenue", label: "Grow revenue", description: "Bring in more sales." },
  {
    id: "customers",
    label: "Acquire customers",
    description: "Reach new people.",
  },
  {
    id: "workload",
    label: "Reduce workload",
    description: "Get more time back.",
  },
  {
    id: "happiness",
    label: "Improve customer happiness",
    description: "Make every interaction count.",
  },
  {
    id: "growth",
    label: "Grow faster",
    description: "Move promising ideas forward.",
  },
  {
    id: "cash",
    label: "Protect cash flow",
    description: "Keep money available when you need it.",
  },
  {
    id: "brand",
    label: "Build brand awareness",
    description: "Help more people remember you.",
  },
];
export const demoRules: BusinessRule[] = [
  {
    id: "ad-spend",
    category: "Ads",
    label: "Maximum daily ad spend",
    help: "The total daily limit across campaigns.",
    kind: "number",
    value: 500,
    unit: "€",
    min: 0,
    max: 1000000,
    step: 1,
  },
  {
    id: "budget-increase",
    category: "Ads",
    label: "Maximum automatic budget increase",
    help: "The largest increase allowed at one time.",
    kind: "number",
    value: 20,
    unit: "%",
    min: 0,
    max: 100,
    step: 1,
  },
  {
    id: "roas",
    category: "Ads",
    label: "Minimum target ROAS",
    help: "At least €2.50 in revenue for every €1 spent on ads at the default target.",
    kind: "number",
    value: 2.5,
    unit: "x",
    min: 0,
    max: 100,
    step: 0.1,
  },
  {
    id: "pause-ads",
    category: "Ads",
    label: "Automatically pause clearly losing ads",
    help: "When your future limits allow it.",
    kind: "toggle",
    value: true,
  },
  {
    id: "answer-questions",
    category: "Customer service",
    label: "Answer normal questions automatically",
    help: "Routine questions about delivery and products.",
    kind: "toggle",
    value: true,
  },
  {
    id: "refund-limit",
    category: "Customer service",
    label: "Refunds above this amount require approval",
    help: "You review any refund above this limit.",
    kind: "number",
    value: 50,
    unit: "€",
    min: 0,
    max: 1000000,
    step: 1,
  },
  {
    id: "complaints",
    category: "Customer service",
    label: "Complaints",
    help: "Keep sensitive conversations in your hands.",
    kind: "choice",
    value: "Always request approval",
    options: ["Always request approval", "Prepare a reply for review"],
  },
  {
    id: "discount",
    category: "Pricing",
    label: "Never discount more than",
    help: "Your maximum discount on a product.",
    kind: "number",
    value: 20,
    unit: "%",
    min: 0,
    max: 100,
    step: 1,
  },
  {
    id: "margin",
    category: "Pricing",
    label: "Never sell below this profit per order",
    help: "A money amount, not a percentage margin.",
    kind: "number",
    value: 35,
    unit: "€",
    min: 0,
    max: 1000000,
    step: 1,
  },
  {
    id: "profit-warning",
    category: "Finance",
    label: "Warn me if daily profit falls below",
    help: "A heads-up when profit needs attention.",
    kind: "number",
    value: 500,
    unit: "€",
    min: 0,
    max: 1000000,
    step: 1,
  },
  {
    id: "cash-reserve",
    category: "Finance",
    label: "Protect minimum cash reserve",
    help: "Keep this much money available.",
    kind: "number",
    value: 10000,
    unit: "€",
    min: 0,
    max: 100000000,
    step: 100,
  },
];
export const defaultInstructions: AIInstruction = {
  communication: "Simple",
  notifications: "Only important",
  decisions: "Balanced",
  businessInstructions:
    "Never sacrifice profit just to increase revenue.\nCustomer happiness is very important.\nAsk me before spending more than €500/day on ads.",
};
export const defaultDashboard: DashboardPreferences = {
  order: ["attention", "metrics", "performance", "activity", "team"],
  hidden: [],
  density: "comfortable",
};
export const dashboardLabels = {
  attention: "Needs you",
  metrics: "Your numbers",
  performance: "Performance & summary",
  activity: "Live activity",
  team: "Your AI team",
};
export const autonomyOptions = [
  {
    name: "Copilot",
    description:
      "Anti-Nerd analyzes everything but asks before making changes.",
    hint: "You approve every change.",
  },
  {
    name: "Assisted",
    description:
      "Anti-Nerd handles safe everyday tasks automatically and asks before important decisions.",
    hint: "A little help, with you in charge.",
  },
  {
    name: "Autopilot",
    description: "Anti-Nerd can act automatically within limits you define.",
    hint: "Your boundaries come first.",
  },
] as const;
export const founderProcess = [
  "Researching market",
  "Finding opportunities",
  "Comparing competition",
  "Checking margins",
  "Building brand",
  "Building store",
  "Creating launch plan",
  "Creating ads",
  "Ready to launch",
];
